title: Peter Stephenson # your name (or website title) here
#logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist .
  <br><br>
   
  <br><br>
  <a href="https://www.linkedin.com</a> 
  
theme: jekyll-theme-minimal
 
colors:
  crimson: '#900C3F'
